### ISSUE TITLE
Different Preset Variable Sets

### ISSUE THREAD

**Issue by RJuall** [davidrosenblum/Plague-Project#45]
Adding a number of variable presets to demonstrate the functionality of the application or to model specific diseases

**Comment by jpojero** [comment]
Do you want this to be a drop down list of specific diseases that have a preset for everything but sim length?

**Comment by jpojero** [comment]
Dropdown that has custom and more virus to select. When custom is selected allow use to input on all fields. When a virus preset is selected disable all fields except total population, amount initially infected and simulation length
